//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.EF.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_session
    {
        public int Id { get; set; }
        public Nullable<int> FilmId { get; set; }
        public Nullable<System.DateTime> Slot { get; set; }
        public Nullable<int> HallId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Hall Hall { get; set; }
    }
}
